version: '3.8'

services:
  web:
    build: .
    command: python3 project/main.py
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
      - redis


  redis:
    image: redis:alpine3.17

  db:
    image: postgres:alpine3.17
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: