"""Third

Revision ID: 0243376f0c6d
Revises: 5ac2db0e9503
Create Date: 2023-03-29 18:53:55.403487

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

TYPES = [
    ('sent', 'Notification sent'),
    ('read', 'Notification read')
]

# revision identifiers, used by Alembic.
revision = '0243376f0c6d'
down_revision = '5ac2db0e9503'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sqlalchemy_utils.types.choice.ChoiceType(TYPES), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
