"""Second

Revision ID: 091b8eaff926
Revises: 5b1b6a03bb60
Create Date: 2023-02-28 11:19:24.038562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091b8eaff926'
down_revision = '5b1b6a03bb60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
