"""Fivth

Revision ID: 28e8e6e4186c
Revises: 82c08e51bcee
Create Date: 2023-02-28 14:40:20.287310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e8e6e4186c'
down_revision = '82c08e51bcee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
