"""Eleven

Revision ID: 2d4aa7aad295
Revises: 57a1f3e1762a
Create Date: 2023-03-22 13:38:45.554845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d4aa7aad295'
down_revision = '57a1f3e1762a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'quizzes', 'users', ['updated_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.drop_column('quizzes', 'updated_by')
    # ### end Alembic commands ###
