"""nine

Revision ID: 466a2457aa7d
Revises: d09740483056
Create Date: 2023-03-14 13:39:05.660075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466a2457aa7d'
down_revision = 'd09740483056'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('invite_message', sa.String(length=150), nullable=True))
    op.drop_constraint('actions_owner_id_fkey', 'actions', type_='foreignkey')
    op.drop_constraint('actions_company_id_fkey', 'actions', type_='foreignkey')
    op.create_foreign_key(None, 'actions', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('actions', 'owner_id')
    op.drop_constraint('companies_members_company_id_fkey', 'companies_members', type_='foreignkey')
    op.create_foreign_key(None, 'companies_members', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies_members', type_='foreignkey')
    op.create_foreign_key('companies_members_company_id_fkey', 'companies_members', 'companies', ['company_id'], ['id'])
    op.add_column('actions', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'actions', type_='foreignkey')
    op.create_foreign_key('actions_company_id_fkey', 'actions', 'companies', ['company_id'], ['id'])
    op.create_foreign_key('actions_owner_id_fkey', 'actions', 'users', ['owner_id'], ['id'])
    op.drop_column('actions', 'invite_message')
    # ### end Alembic commands ###
