"""Second

Revision ID: 5ac2db0e9503
Revises: 959bdd964a17
Create Date: 2023-03-27 19:18:57.723584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac2db0e9503'
down_revision = '959bdd964a17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizz_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_of_passage', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('quizz_id', sa.Integer(), nullable=True),
    sa.Column('general_result', sa.Float(precision=2), nullable=True),
    sa.Column('amount_of_questions', sa.Integer(), nullable=True),
    sa.Column('amount_of_correct_answers', sa.Integer(), nullable=True),
    sa.Column('avg', sa.Float(precision=2), nullable=True),
    sa.Column('amount_of_questions_quizz', sa.Integer(), nullable=True),
    sa.Column('amount_of_correct_answers_quizz', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quizz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizz_results_id'), 'quizz_results', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quizz_results_id'), table_name='quizz_results')
    op.drop_table('quizz_results')
    # ### end Alembic commands ###
